name: Emergency Rollback

on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'Revision number (deixe vazio para anterior)'
        required: false
        type: string

jobs:
  rollback:
    name: Rollback Production
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
          --zone ${{ secrets.GKE_ZONE }}
    
    - name: Show current deployment info
      run: |
        echo "=== ESTADO ATUAL ==="
        kubectl get deployment devops-app -n devops-app -o wide
        kubectl rollout history deployment/devops-app -n devops-app
    
    - name: Perform rollback
      run: |
        if [ -z "${{ github.event.inputs.revision }}" ]; then
          echo "Fazendo rollback para versão anterior..."
          kubectl rollout undo deployment/devops-app -n devops-app
        else
          echo "Fazendo rollback para revision ${{ github.event.inputs.revision }}..."
          kubectl rollout undo deployment/devops-app \
            --to-revision=${{ github.event.inputs.revision }} \
            -n devops-app
        fi
    
    - name: Wait for rollback completion
      run: |
        kubectl rollout status deployment/devops-app -n devops-app --timeout=300s
    
    - name: Verify rollback
      run: |
        echo "=== ESTADO APÓS ROLLBACK ==="
        kubectl get pods -n devops-app -l app=devops-app
        kubectl get deployment devops-app -n devops-app -o wide
        
        EXTERNAL_IP=$(kubectl get service devops-app-service -n devops-app \
          -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        
        if curl -f http://$EXTERNAL_IP/health; then
          echo "Rollback realizado com sucesso"
        else
          echo "Rollback pode ter falhado - verificar manualmente"
          exit 1
        fi